# Generated by Django 3.2.8 on 2022-01-11 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mascotas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('email', models.EmailField(max_length=200)),
                ('telefono', models.CharField(max_length=200)),
                ('fecha_reserva', models.DateTimeField(blank=True, default=None, null=True)),
                ('nombre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mascotas.mascota')),
            ],
            options={
                'db_table': 'reservacion_citas',
            },
        ),
    ]
