# Generated by Django 3.2.8 on 2022-01-11 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocupacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservacion',
            name='fecha_reserva',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
