# Generated by Django 3.2.8 on 2022-01-11 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocupacion', '0002_alter_reservacion_fecha_reserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservacion',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
