# Generated by Django 3.2.8 on 2022-01-11 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_articulo', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'inventario_articulo',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('telefono', models.CharField(max_length=200)),
                ('cargo', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'empleado',
            },
        ),
        migrations.CreateModel(
            name='RegistroArticulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disponible', models.BooleanField(default=True)),
                ('date_use', models.DateTimeField(blank=True, default=None, null=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.empleado')),
                ('name_articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.articulo')),
            ],
            options={
                'db_table': 'registro_articulo',
            },
        ),
    ]
