# Generated by Django 3.2.8 on 2022-01-11 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='edad',
            field=models.CharField(max_length=100),
        ),
    ]
